"""create expense_categories table

Revision ID: 69132edf3564
Revises: 47271149c5f0
Create Date: 2020-10-08 16:10:28.990202

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69132edf3564'
down_revision = '47271149c5f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('expense_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('expense_categories')
    # ### end Alembic commands ###
